services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: always
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        depends_on:
            - db
        ports:
            - "${WORKSPACE_VUE_CLI_SERVE_HOST_PORT:-8080}:8080"
            - "${WORKSPACE_VUE_CLI_UI_HOST_PORT:-8001}:8000"
            - "${WORKSPACE_VITE_PORT:-5173}:5173"
        environment:
            - APP_ENV=${APP_ENV:-local}
            - CONTAINER_ROLE=app
        networks:
            - laravel

    db:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: nginx_server
        restart: always
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

volumes:
    mysql_data:

networks:
    laravel:
        driver: bridge
